WHEEL_DIAMETER = 63  # mm

MAX_STEER = 35

CHECK_DISTANCE = 1300  # mm
START_CHECK_DISTANCE = 500  # mm

OBSTACLE_SAFE_DISTANCE_FROM_WALLS = 200  # mm
OPEN_SAFE_DISTANCE_FROM_WALLS = 100  # mm


OPEN_HIGH_SPEED = -1200
OPEN_LOW_SPEED = -1200

OBSTACLE_HIGH_SPEED = -1100
OBSTACLE_LOW_SPEED = -900

MIN_OBSTACLE_AREA = 150

OPEN_GYRO_KP = 1.2

# OBSTACLE_COUNTER_GYRO_KP = 0.4
# OBSTACLE_COUNTER_GYRO_KP = 0.8

N_CONSEQ_COLORS = 2

# v1 (REGIONAL)
# OBS_PIXY_KP = 0.3
# OBSTACLE_GYRO_KP = 1.2
# OBS_ULTRASONIC_KP = 0.2

# v2
# OBS_PIXY_KP = 1.7
# OBSTACLE_GYRO_KP = 0.8
# OBS_ULTRASONIC_KP = 0.3

# v3
OBS_PIXY_KP = 1.7
OBSTACLE_GYRO_KP = 0.8
OBS_ULTRASONIC_KP = 0.8